name: VISTRA local
values:
  - key: base_url
    value: 'http:\\localhost:8000'
  - key: user_id
    value: STF001
  - key: access_token
    value: ''
  - key: refresh_token
    value: ''
  - key: patient_id
    value: ''
  - key: patient_birthday
    value: ''
  - key: patient_age
    value: ''
  - key: appointment_id
    value: ''
  - key: dental_visit_id
    value: ''
